### ISSUE TITLE
`/block` & `/block/transaction`

### ISSUE THREAD

**Issue by AlanVerbner** [input-output-hk/cardano-rosetta#268]
# Description

In order to support Multi Assets transactions, we need return them when querying for transactions. Please refer to the schema proposed in #280 

### Outputs

- When querying for transaction outputs, also `ma_tx_out` needs to be joined by `ma_tx_out.tx_out_id = tx.id`
- Token symbol should be returned as an hex string (encoding is not defined in the db)
- [This](https://github.com/input-output-hk/cardano-rosetta/blob/master/cardano-rosetta-server/src/server/db/blockchain-repository.ts#L241) code needs to be changed in order to also query for the MA. It might be a good approach to get MA tx out when querying for tx out (`lEFT JOIN`) and introduce MAs when `parseOutputsRow`
- Keep in mind that a single unspent might be related to many MA entries.

### Inputs

- When returning inputs, we are also returning the amount being spent. 
- When querying for tx inputs we also need to join with `ma_tx_out` as we need to include tokens information. 
- Same parsing as Outputs will need to be performed.

**Comment by kevinhammond** [comment]
Note that there is no default scaling/exchange rate for different tokens within a policy.

For example, you might choose a policy (let's say "KH") with ada and lovelace token names.  There is no way to enforce that 1 KH.ada is equivalent in value to 1,000,000 KH.lovelace (this may come with a smart contract).

**Comment by kevinhammond** [comment]
It is not possible to have negative values for coin amounts (though the amount may be 0, except for ada because of the minutxo requirement).  0 is equivalent to the token type not being present.

When minting tokens, a negative value indicates that tokens are burnt.  It is possible to mint and burn at the same time.

**Comment by kevinhammond** [comment]
I don't understand 'coin_created' - is this minting or simply that a new token name has been encountered?
If minting, you will need burning as well (which could be a negative mint value if preferred).

**Comment by kevinhammond** [comment]
"MyCoin" will not be enough as a string - you will need to record the policy id hash somewhere, so you can uniquely identify the coins

**Comment by kevinhammond** [comment]
withdrawalAmount etc are always denominated in ada

**Comment by kevinhammond** [comment]
Note that a single transaction may handle many different native token types (so make sure that the values are replicated).  For example, mint token A, burn token B, send tokens C, D and some ada to different addresses.

**Comment by james-iohk** [comment]
`mutliassets` :)

**Comment by AlanVerbner** [comment]
> Note that there is no default scaling/exchange rate for different tokens within a policy.
> 
> For example, you might choose a policy (let's say "KH") with ada and lovelace token names. There is no way to enforce that 1 KH.ada is equivalent in value to 1,000,000 KH.lovelace (this may come with a smart contract).

Noted. We don't have such logic in Cardano Rosetta.

**Comment by AlanVerbner** [comment]
> It is not possible to have negative values for coin amounts (though the amount may be 0, except for ada because of the minutxo requirement). 0 is equivalent to the token type not being present.
> 
> When minting tokens, a negative value indicates that tokens are burnt. It is possible to mint and burn at the same time.

Rosetta has a separate semantics that are mapped to Cardano ones. For example: a `burn` might be expressed as a positive value although it will be mapped to a negative one when translating to a Cardano tx. BTW, mint and burn are out of scope.

**Comment by AlanVerbner** [comment]
> I don't understand 'coin_created' - is this minting or simply that a new token name has been encountered?
> If minting, you will need burning as well (which could be a negative mint value if preferred).

`coin_created` means that a new unspent has been created

**Comment by AlanVerbner** [comment]
> "MyCoin" will not be enough as a string - you will need to record the policy id hash somewhere, so you can uniquely identify the coins

you are completely right! I missed that value when creating the example, in the spec written above it's stated as metadata

**Comment by AlanVerbner** [comment]
> Note that a single transaction may handle many different native token types (so make sure that the values are replicated). For example, mint token A, burn token B, send tokens C, D and some ada to different addresses.

yes! although we won't let people to mint or burn using Cardano Rosetta in v3, do you think that will be an issue?

**Comment by kevinhammond** [comment]
> > I don't understand 'coin_created' - is this minting or simply that a new token name has been encountered?
> > If minting, you will need burning as well (which could be a negative mint value if preferred).
> 
> `coin_created` means that a new unspent has been created

So refers to UTxO rather than coins in the multi-asset token sense.  My confusion!

**Comment by kevinhammond** [comment]
> > Note that a single transaction may handle many different native token types (so make sure that the values are replicated). For example, mint token A, burn token B, send tokens C, D and some ada to different addresses.
> 
> yes! although we won't let people to mint or burn using Cardano Rosetta in v3, do you think that will be an issue?

No, you can keep things minimal initially!  It was just so you were aware that you might end up with multiple kinds of value (perhaps spread across different outputs, sending some tokens to one address, some to another etc).

**Comment by rhyslbw** [comment]
> Token symbol should be returned as an hex string (encoding is not defined in the db)

UTF-8

**Comment by AlanVerbner** [comment]
> > Token symbol should be returned as an hex string (encoding is not defined in the db)
> 
> UTF-8

@rhyslbw .. as we discussed with @kevinhammond it's not ok to encode it as UTF-8

**Comment by kevinhammond** [comment]
You can use an encoding like UTF-8 for transmission, just don't expect the user display to necessarily be as intended by the token issuer.  There's some work going on to define the expected display (and node CLI input) formats using the metadata identity server.  I expect this to also be policyID dependent.  So, for now, keep things simple (e.g. use byte strings, display/input everything as bytes (or display/input alphanumeric asset names, but be aware of the traps), use UTF-8 for encoding transmitted byte strings)
