### ISSUE TITLE
`/construction/parse`

### ISSUE THREAD

**Issue by AlanVerbner** [input-output-hk/cardano-rosetta#270]
# Description

`/contruction/parse` needs to be updated in order to parse the MA unspents from both signed and unsigned transactions.

## Implementation details

- Parsing and mapping needs to be updates as it's being done already.
- See #268 to see how mapping is being introduced in `output` operations

**Comment by kevinhammond** [comment]
Again, watch out for special characters in the token names.  I'm assuming there is eg some JSON or data structure for the token bundles in the UTxOs.  I don't think you will need to deal with replicated token names under the same policy ID, though it might be theoretically possible to create this
