### ISSUE TITLE
`/construction/preprocess`

### ISSUE THREAD

**Issue by AlanVerbner** [input-output-hk/cardano-rosetta#272]
# Description

`/construction/preprocess` needs to update operations parsing and transaction encoding in order to include MA. Such methods are used to calculate transaction size.

## Implementation details

- Transaction encoding should be updated here with latest `serialization-lib` version

**Comment by kevinhammond** [comment]
Be careful if parsing the content of the token bundles - token names may contain special characters that could cause problems if handled carelessly (quotes, backslash etc)
