### ISSUE TITLE
`/construction/submit`

### ISSUE THREAD

**Issue by AlanVerbner** [input-output-hk/cardano-rosetta#273]
# Description

The command used when invoking `cardano-cli` to send the transaction will need to be updated. 

## Implementation details

1. Remove the `--shelley` flag as it's deprecated
2. Check the transaction sending actually works

**Comment by kevinhammond** [comment]
Yes, submission should be the same.  You will want to make sure that the raw transaction is built with the correct era flag, of course:

``cardano-cli transaction build-raw ... --mary-era``

if you are using the CLI there
