### ISSUE TITLE
Use test data from launchpad

### ISSUE THREAD

**Issue by AlanVerbner** [input-output-hk/cardano-rosetta#276]
# Description

We are currently using a `mainnet` snapshot to generate some test scenarios. This is no longer useful for MA as current transactions are only present in `launchpad` network. This task is about defining a way to improve this process.

## Implementation details

Alternatives:

1. Allow tests to rely upon multiple snapshots.
2. Load data from different sources into a single snapshot (maybe it's a little bit cumbersome).
3. Let snapshots to be optional.

**Comment by kevinhammond** [comment]
Yes, we can't transfer addresses to the launchpad to get quick test setups.  Until we have the hard fork, multi-asset token bundles can't be tested on mainnet.  

One option would be to replicate from a snapshot onto a testnet, then fork that
Another option is to replicate the setup that you require by using automated scripts
