### ISSUE TITLE
send-transaction-example generates addresses that cardano-addresses can't inspect

### ISSUE THREAD

**Issue by johnmathews** [input-output-hk/cardano-rosetta#331]
The example `send-transaction-example` runs without any problems.
However if I use the cardano-addresses tool to inspect either the secret key or the public key, the tool gives the following errors. I'm confused by this because the example will run with this secret key.

The secret key in the send-transaction-example.ts: 
`41d9523b87b9bd89a4d07c9b957ae68a7472d8145d7956a692df1a8ad91957a2c117d9dd874447f47306f50a650f1e08bf4bec2cfcb2af91660f23f2db912977`

running the following command:
`docker run --rm -i cardano-address key inspect <<< $(echo "41d9523b87b9bd89a4d07c9b957ae68a7472d8145d7956a692df1a8ad91957a2c117d9dd874447f47306f50a650f1e08bf4bec2cfcb2af91660f23f2db912977")`

give this error:
`user error (Bech32 error: Invalid character(s) in string:
41d9523b87b9bd89a4d07c9b957ae68a7472d8145d7956a692df1a8ad91957a2c117d9dd874447f47306f50a650f1e08bf4bec2cfcb2af91660f23f2db912977)`

Then, if I inspect a public key that the script derives from the above secret key, I get the following error:
`docker run --rm -i cardano-address key inspect <<< $(echo "c117d9dd874447f47306f50a650f1e08bf4bec2cfcb2af91660f23f2db912977")
user error (Bech32 error: string is too short)`

What is the problem here?

Incidentally, I tried to inspect these addresses because I cannot make the example run while using keys and addresses that I derive myself. I need to generate sets of addresses and allocated them to users. Is there a more convenient way to do this than generating the keys using cardano-address and then passing the keys/addresses to a cardano-rosetta script? perhaps by parsing an argument to NaCL (tweetnacl)?

**Comment by KtorZ** [comment]
cardano-address mainly uses bech32-encoded data for interfacing to avoid shooting yourself in the foot. There are many keys and hashes floating around in Cardano, and from a binary standpoint, they all look the same. Any sequence of 32 bytes is a potentially valid Ed25519 verification key and any sequence of 28 bytes is a potentially valid blake2b digest. 

The error message from cardano-address isn't optimal here, it's trying to decode the given string as a bech32 input, chokes on it and return the bech32 error. What it should say instead is: "The input should be encoded in Bech32 using one of the follow prefixes: ..., but it isn't". 

You can rapidly encode hex to string if you need to and know what binary data you're manipulating using: https://github.com/input-output-hk/bech32/#bech32-command-line

**Comment by johnmathews** [comment]
Ooo thanks! I wasn't aware that there was different encodings. Is there somewhere I can read more about which encodings are used?  The `bech32 --help` is a bit too terse for me.

I've been trying to derive offline the same addresses that cardano-rosetta would derive. (I asked a [question](https://stackoverflow.com/questions/66874521/how-to-construct-cardano-transaction-using-cardano-rosetta-and-cardano-addresses) about it on SO).

If the same private key is used in cardano-addresses and in cardano-rosetta then each tool derives a different payment address. Do you know why?

My process is:

**cardano-addresses:**
1. -> phrase.prv `cardano-address recovery-phrase generate --size 15 > phrase.prv`
2. phrase.prv -> root.xsk `cat phrase.prv | cardano-address key from-recovery-phrase Shelley | tee root.xsk`
3. root.xsk -> utxo.prv  `cardano-address key child 1852H/1815H/0H/0/0 < root.xsk | tee utxo.prv`
4. utxo.prv -> addr.xvk `cardano-address key public --with-chain-code < utxo.prv | tee addr.xvk`
5. addr.xvk -> payment.addr `cardano-address address payment --network-tag testnet < addr.xvk > payment.addr`

**cardano-rosetta:**
* Inspecting utxo.prv shows the extended private key.  `cardano-address key inspect < utxo.prv `
    This can be given to cardano-rosetta (it replaces the private key in the example scripts).
    The public key derived by cardano-rosetta is simply the second half of the extended private key.
* cardano-rosetta calls `/construction/derive` and receives a valid payment address (call it `add1`).

Why is `add1` not the same as `payment.addr`?

**Comment by zxpectre** [comment]
@johnmathews did you find a way? 
I've been following in your footsteps at forum, SO and here. I'm stuck with the same problem with rosetta and cardano-address, I believe the problem is the derived private key generated with cardano-address, because even creating pub key and address using rosetta instead of cardano-address causes the same tx submit rejection:

```
{"level":50,"time":1621313138512,"pid":96,"hostname":"0af846f76f09","reqId":2208,"shortMessage":"Command failed with exit code 1: /usr/local/bin/cardano-cli transaction submit --tx-file /tmp/b0d1b17c-625f-41f7-b623-36b81168a691 --testnet-magic 1097911063","command":"/usr/local/bin/cardano-cli transaction submit --tx-file /tmp/b0d1b17c-625f-41f7-b623-36b81168a691 --testnet-magic 1097911063","exitCode":1,"stdout":"","stderr":"Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey \"\\220S@\\169\\243%cN\\252z\\a0/\\203\\152\\208\\138H\\138\\223N\\ESCX\\248\\205\\242\\128\\232\\SOP\\242\\156\"))]))]","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"msg":"[submitTransaction] Command failed","stack":"Error: Command failed with exit code 1: /usr/local/bin/cardano-cli transaction submit --tx-file /tmp/b0d1b17c-625f-41f7-b623-36b81168a691 --testnet-magic 1097911063\nShelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey \"\\220S@\\169\\243%cN\\252z\\a0/\\203\\152\\208\\138H\\138\\223N\\ESCX\\248\\205\\242\\128\\232\\SOP\\242\\156\"))]))]\n    at makeError (/cardano-rosetta-server/node_modules/execa/lib/error.js:59:11)\n    at handlePromise (/cardano-rosetta-server/node_modules/execa/index.js:114:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","type":"Error","v":1}
{"level":50,"time":1621313138512,"pid":96,"hostname":"0af846f76f09","reqId":2208,"msg":"Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey \"\\220S@\\169\\243%cN\\252z\\a0/\\203\\152\\208\\138H\\138\\223N\\ESCX\\248\\205\\242\\128\\232\\SOP\\242\\156\"))]))]","stack":"Error: Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey \"\\220S@\\169\\243%cN\\252z\\a0/\\203\\152\\208\\138H\\138\\223N\\ESCX\\248\\205\\242\\128\\232\\SOP\\242\\156\"))]))]\n    at Object.<anonymous> (/cardano-rosetta-server/dist/src/server/utils/cardano/cli/cardanonode-cli.js:60:31)\n    at Generator.throw (<anonymous>)\n    at rejected (/cardano-rosetta-server/dist/src/server/utils/cardano/cli/cardanonode-cli.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","type":"Error","v":1}
{"level":50,"time":1621313138512,"pid":96,"hostname":"0af846f76f09","reqId":2208,"code":5006,"retriable":true,"details":{"message":"Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey \"\\220S@\\169\\243%cN\\252z\\a0/\\203\\152\\208\\138H\\138\\223N\\ESCX\\248\\205\\242\\128\\232\\SOP\\242\\156\"))]))]"},"msg":"[errorHandler] An error ocurred and will be sent as response","stack":"Error: Error when sending the transaction\n    at Object.exports.buildApiError (/cardano-rosetta-server/dist/src/server/utils/errors.js:86:56)\n    at Object.sendTransactionError (/cardano-rosetta-server/dist/src/server/utils/errors.js:108:51)\n    at /cardano-rosetta-server/dist/src/server/controllers/construction-controller.js:170:46\n    at Generator.throw (<anonymous>)\n    at rejected (/cardano-rosetta-server/dist/src/server/controllers/construction-controller.js:6:65)","type":"Error","v":1}

```  
So I believe the only thing in common between the 2 key generation paths is the private child key, well and mnemonic itself.

I'm on cardano-rosetta 1.2.1

Can anyone give us a hint? 
@KtorZ do we need to decode from bech32 to something else to be able to use this child private key generated on cardano-address on rosetta?

**Comment by KtorZ** [comment]
@AlanVerbner @rhyslbw

Does cardano-rosetta actually support Ed25519-bip32 (or so-called extended keys) signatures?

**Comment by johnmathews** [comment]
@zxpectre I didn't find a way. 😞 I found this problem so frustrating that I moved on to a different task, sorry I don't have better news. I would still like to know how to solve it though.

**Comment by rhyslbw** [comment]
_Sorry for the radio silence on this issue guys. @KtorZ asked me to look into this after his initial response, so has been on me to investigate._

When generating an address the public key is being derived here:
https://github.com/input-output-hk/cardano-rosetta/blob/d4042d84566b779826c28f10c406f9393f73f431/cardano-rosetta-server/src/server/services/cardano-services.ts#L376

`CardanoWasm.Bip32PublicKey` should resolve this, but I'll need to setup a test to confirm.

**Comment by zxpectre** [comment]
Please @rhyslbw, can you help us?

 _O alguien de Atix quizás?_

I've spent 2 weeks now trying to use **cardano-rosetta** with derived accounts and addresses  and I swear i've tried tons of key generation/derivations combinations, first using **cardano-addresses** and then using emurgo's **cardano-serialization-lib-nodejs** , and as well as John, I believe **rosetta** may be working with derived addresses.

The only way I've made rosetta to submit a valid tx is by creating a single private key using:
```
const keys= NaCl.sign.keyPair();
const privk=Buffer.from( keys.secretKey ).toString('hex');
const pubk=Buffer.from( keys.publicKey ).toString('hex');
const addr  = await cardano.constructionDerive( //from examples/commons.ts
    network,
    pubk
 );
``` 
I'm using `@emurgo/cardano-serialization-lib-nodejs`, `tweetnacl`,  and `bip39` on JS, and I'm trying to make examples/ma-transfer-example.ts to work but with derived accounts and addresses.

Every success in signing the tx, gets rejected by **rosetta** with this kind of error:
```"Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey \"\\220S@\\169\\243%cN\\252z\\a0/\\203\\152\\208\\138H\\138\\223N\\ESCX\\248\\205\\242\\128\\232\\SOP\\242\\156\"))]))]"```

Any help will be much appreciated!

**Comment by AlanVerbner** [comment]
Hi @zxpectre and @johnmathews,

`cardano-rosetta` sticks to Rosetta spec so you need to send a 32 bytes public key. Actually they key generation and the signing process is pushed to the clients by design. For example this implementation is compliant with `rosetta-cli check:construction` and I don't know how do they sign.

So, the answer to the following question is yes, because the signing logic nor the key generation 

> @AlanVerbner @rhyslbw
> 
> Does cardano-rosetta actually support Ed25519-bip32 (or so-called extended keys) signatures?

That being said I'll try to generate an example that uses `cardano-address`

**Comment by AlanVerbner** [comment]
@zxpectre , @johnmathews 

Please take a look at the PR I've just opened that shows an example that's compliant with `cardano-addresses` values. Please keep in mind it hasn't been reviewed nor approved yet.

**Comment by james-iohk** [comment]
#376 has now been tested and approved :+1:

**Comment by zxpectre** [comment]
Thanks @AlanVerbner  ! totaly make sense now, I was missing the part where you used CardanoWasm to generate the right signatures. Thanks for your time, I think this will be usefull to many people.

**Comment by rhyslbw** [comment]
Done in #376
