### ISSUE TITLE
An error occurred for request 868: Operation searchTransactions not implemented

### ISSUE THREAD

**Issue by rajqumar** [input-output-hk/cardano-rosetta#374]
I am trying to search for a transaction using id or hash of the transaction, but calling this endpoint /search/transaction gives the above error.

Here's my request
` {
        "network_identifier": {
            "blockchain": "cardano",
            "network": "testnet",
        },
        "operator": "or",
        "max_block": 5,
        "offset": 5,
        "limit": 5,
        "transaction_identifier": {
            "hash": "2c3b72b1eb733edd7d8edfbcdb25dab20cd310293dd62208eb7bf9b7dcaaf1d2"
        },
        "account_identifier": {
            "address": "addr_test1qr2dlzychjm4dzqfqmcsxt4ktxel5yhcpm2733s7cmjk0tcxu2hyfhlkwuxupa9d5085eunq2qywy7hvmvej456flknsqwyjd0",
            "metadata": {}
        }
    }`

**Comment by james-iohk** [comment]
Hi @rajqumar. Correct, the Indexer endpoints are not currently implemented. These were introduced in Rosetta API v1.4.7, our current implementation is targeting v1.4.4. We are in the process of releasing an update that will bring us inline with v1.4.10. However, we decided to not implement the Indexer endpoints just yet. These may be introduced in a future release.
