### ISSUE TITLE
Error fetching single transaction details via id or hash 

### ISSUE THREAD

**Issue by rajqumar** [input-output-hk/cardano-rosetta#375]
curl $BASEURL/api/txs/summary/382a5274ebf102910c6c923a8b11f108e79ecedb5d7433cd0dd15a8a443f0fa5
this command does not works and neither the rosetta indexer API => /search/transactions work.

For Rosetta /search/transactions
request: `    let data = {
        "network_identifier": {
            "blockchain": "cardano",
            "network": "testnet",
        },
        "operator": "or",
        "max_block": 5,
        "offset": 5,
        "limit": 5,
        "transaction_identifier": {
            "hash": "2c3b72b1eb733edd7d8edfbcdb25dab20cd310293dd62208eb7bf9b7dcaaf1d2"
        },
        "account_identifier": {
            "address": "addr_test1qr2dlzychjm4dzqfqmcsxt4ktxel5yhcpm2733s7cmjk0tcxu2hyfhlkwuxupa9d5085eunq2qywy7hvmvej456flknsqwyjd0",
            "metadata": {}
        }
    }`

Response: `  details: {
    message: 'An error occurred for request 905: Operation searchTransactions not implemented'
  }
}`

**Comment by james-iohk** [comment]
Hi @rajqumar. Is this highlighting a different issue to #374?

**Comment by rajqumar** [comment]
> Hi @rajqumar. Is this highlighting a different issue to #374?

Yes, same but the curl command was added which is also not working

**Comment by rajqumar** [comment]
> Hi @rajqumar. Is this highlighting a different issue to #374?

How can we fetch single transaction details ? I want the sender address, fee, timestamp and no of confirmations for single transaction ?

**Comment by james-iohk** [comment]
@rajqumar I think you have already started looking at [cardano-graphql](https://github.com/input-output-hk/cardano-graphql), this would be my recommendation for fetching transaction details. [See some example queries here](https://github.com/input-output-hk/cardano-graphql/tree/master/packages/api-cardano-db-hasura/src/example_queries/transactions)

**Comment by rajqumar** [comment]
> @rajqumar I think you have already started looking at [cardano-graphql](https://github.com/input-output-hk/cardano-graphql), this would be my recommendation for fetching transaction details. [See some example queries here](https://github.com/input-output-hk/cardano-graphql/tree/master/packages/api-cardano-db-hasura/src/example_queries/transactions)

When we submit a raw transaction via rosetta we get only transaction hash in response, and the /block/transaction route needs block index and hash, how can we automate this ?

**Comment by james-iohk** [comment]
> When we submit a raw transaction via rosetta we get only transaction hash in response, and the /block/transaction route needs block index and hash, how can we automate this ?

You can use `current_block_identifier` from /network/status response along with this transaction hash. If "Transaction not found" then it may not yet be included on-chain.
