### ISSUE TITLE
Alonzo start fail

### ISSUE THREAD

**Issue by BomaxChen** [input-output-hk/cardano-rosetta#422]
Hi, I build cardano-rosetta from source and checkout to 1.4.0-beta.0,  then 

`docker build --build-arg NETWORK=alonzo-purple -t cardano-rosetta:1.4.0-beta.0-alonzo-purple .`
`docker run -d \
  --name cardano-rosetta-alonzo-purple \
  -p 8082:8080 \
  -v cardano-rosetta-alonzo-purple:/data \
  --shm-size=4g \
  cardano-rosetta:1.4.0-beta.0-alonzo-purple` 

but get the following error msg below
``` [2021-08-25 06:43:02.39 UTC] Domain: "relays.alonzo-purple.dev.cardano.org" Application Exception: 18.142.32.1:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 0, blockPointHash = e25b7696d4500fa423f387041a52488739edecefc29d6d13872866b599116064})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra Z (WrapLedgerErr {unwrapLedgerErr = ChainValidationGenesisHashMismatch (GenesisHash {unGenesisHash = 6d58e8c626cb355ac2a4b040e1adb8266753a69f63593274e4558d6bd0c41eac}) (GenesisHash {unGenesisHash = 570b0e27e60daa224088e0d3afce5dce98b62f6280c21b9074797ef61eab64b2})})))) ```

please help me to solve this issue, is there any step I go wrong?

**Comment by ZhangxyCC** [comment]
@rhyslbw will we have a testnet explorer for alonzo testnet?
