### ISSUE TITLE
Requirements of Cardano-rosetta

### ISSUE THREAD

**Issue by slashramin** [input-output-hk/cardano-rosetta#443]
what are the **requirements** of cardano-rosetta
I have 160Gb SSD and its full.
**cardano-db-sync** storage requirement is 80Gb ssd.
**cardano-node** storage requirement is 50Gb ssd.
why **cardano-rosetta** needs more than 160gb space? 
started **cardano-rosetta** with this command:

`docker run --name cardano-rosetta -p 8080:8080 -v cardano-rosetta:/data --shm-size=2g inputoutput/cardano-rosetta:1.5.0`

my server hardware information is : 
32Gb Ram, 8 core Cpu, 160Gb SSD

**Comment by rhyslbw** [comment]
Minimum requirements are now published with the release notes
https://github.com/input-output-hk/cardano-rosetta/releases/tag/1.6.0
