### ISSUE TITLE
How to add custom metadata to a transaction ?

### ISSUE THREAD

**Issue by bcoste** [input-output-hk/cardano-rosetta#462]
I try to add a custom metadata to my transaction but my metadata is missing when I get the transaction in the testnet explorer.

I tryed to add my custom metadata in several calls :
- /construction/preprocess : in the response options, only relative_ttl and transaction_size attributes are present
- /contruction/metadata : in the response metadata, my custom metadata are lost
- /construction/payloads

Here is my java code I use for setting the metadata :
> Map<String,Object> metadata = req.getMetadata();
> metadata.put("relative_ttl", 5000);
> 
> //test 1
> metadata.put("digest", digest);
> 
> //test 2
> Map<String,Object> mapStrVal = new HashMap<>();
> mapStrVal.put("digest2", digest);
> metadata.put("0", mapStrVal);
> 
> //test 3
> Map<String,Object> mapStrVal2 = new HashMap<>();
> mapStrVal2.put("name", "digest3");
> mapStrVal2.put("completed", 0);
> metadata.put("123", mapStrVal2);

**Comment by james-iohk** [comment]
@bcoste There is no support for custom transaction metadata with Cardano Rosetta.
All of the metadata fields are related to either: staking, pool registration, asset transfer or vote operations. [See here](https://github.com/input-output-hk/cardano-rosetta/blob/master/cardano-rosetta-server/src/server/openApi.json#L1088) for all the fields you can set.
