### ISSUE TITLE
Is Cardano Rosetta 1.7.1 ready for the Vasil Hard Fork?

### ISSUE THREAD

**Issue by jjambazov-bc** [input-output-hk/cardano-rosetta#486]
Hey, I see that Cardano Rosetta 1.7.1 bundles [cardano-node@1.33.0](https://github.com/input-output-hk/cardano-node/releases/tag/1.33.0) and [cardano-db-sync@12.0.0](https://github.com/input-output-hk/cardano-db-sync/releases/tag/12.0.0). Is this ready for the upcoming Vasil hard fork? Or is [cardano-node@1.35.0](https://github.com/input-output-hk/cardano-node/releases/tag/1.35.0) needed for the fork?

**Comment by rhyslbw** [comment]
No, `1.8.0`, expected this week, will be the minimum compatible version for the Babbage era.

**Comment by jjambazov-bc** [comment]
Is the release of `1.8.0` being delayed, can we expect it this week?

**Comment by rhyslbw** [comment]
The release of dependent services is getting quite close, so it shouldn't be too much longer now.

**Comment by 0xtrossets** [comment]
@rhyslbw 
`1-8-stable` is not working on testnet (post Vasil). Should I just build off of `master`?

**Comment by rhyslbw** [comment]
The `1-8-stable` branch was pushed a bit soon. I've removed it, as we may be now moving to `2.0.0` with the introduction of Ogmios to submit transactions, which forces a potential breaking change with error handling. _testnet_ compatibility requires the _master_ branch until the next release.
