### ISSUE TITLE
Search transactions endpoint on fully synced mainnet tooks > 1min

### ISSUE THREAD

**Issue by miroslavm87** [input-output-hk/cardano-rosetta#501]
Hi, search transactions endpoint on fully synced mainnet tooks > 1min. Need query optimisation.

**Comment by 0xtrossets** [comment]
Which version are you running?

**Comment by miroslavm87** [comment]
inputoutput/cardano-rosetta:1.8.1

**Comment by 0xtrossets** [comment]
I'm seeing the same issue.

**Comment by Godspeed-exe** [comment]
@miroslavm87 @0xtrossets can you give us an example of the query which takes more then 1 minute?

**Comment by miroslavm87** [comment]
> @miroslavm87 @0xtrossets can you give us an example of the query which takes more then 1 minute?
/search/transactions
body:

{
    "network_identifier": {
        "blockchain": "cardano",
        "network": "mainnet"
    },
    "address":"addr1vy3qpx09uscywhppj5vp08hu0ekg9zwmq2ysfq6qyh2mpps865j6t"
}

**Comment by rhyslbw** [comment]
A performance improvement has been determined and we're working on implementation now, with a patch release to follow.
